### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'text'

### ISSUE THREAD

**Issue by ViktorPavlovA** [ketai-dhr/arducam-camera-bug-report#3]
```./arducam-camera-bug-report
Traceback (most recent call last):
  File "./arducam-camera-bug-report", line 142, in <module>
    cmd_out = run_prog(args.c, args.t)
  File "./arducam-camera-bug-report", line 55, in run_prog
    stderr=subprocess.STDOUT, errors='ignore')
TypeError: __init__() got an unexpected keyword argument 'text'
```

`pip3 list` looks like:

```
apt-clone (0.2.1)
apturl (0.5.2)
asn1crypto (0.24.0)
beautifulsoup4 (4.6.0)
blinker (1.4)
Brlapi (0.6.6)
certifi (2023.11.17)
chardet (3.0.4)
charset-normalizer (2.0.12)
cryptography (2.1.4)
cupshelpers (1.0)
cycler (0.10.0)
Cython (3.0.8)
decorator (4.1.2)
defer (1.0.6)
distro-info (0.18ubuntu0.18.04.1)
durationpy (0.6)
feedparser (5.2.1)
graphsurgeon (0.4.5)
html5lib (0.999999999)
httplib2 (0.9.2)
idna (3.6)
Jetson.GPIO (2.0.17)
keyring (10.6.0)
keyrings.alt (3.0)
language-selector (0.1)
launchpadlib (1.10.6)
lazr.restfulclient (0.13.5)
lazr.uri (1.0.3)
louis (3.5.0)
lxml (4.2.1)
macaroonbakery (1.1.3)
Mako (1.0.7)
MarkupSafe (1.0)
matplotlib (2.1.1)
numpy (1.13.3)
oauth (1.0.1)
oauthlib (2.0.6)
onboard (1.4.1)
PAM (0.4.2)
pandas (0.22.0)
pip (9.0.1)
protobuf (3.0.0)
pycairo (1.16.2)
pycrypto (2.6.1)
pycups (1.9.73)
pygobject (3.26.1)
PyICU (1.9.8)
PyJWT (1.5.3)
pymacaroons (0.13.0)
PyNaCl (1.1.2)
pyparsing (2.2.0)
pyRFC3339 (1.0)
python-apt (1.6.5+ubuntu0.6)
python-dateutil (2.8.2)
python-debian (0.1.32)
pytz (2018.3)
pyxattr (0.6.0)
pyxdg (0.25)
PyYAML (3.12)
pyzed (1.3.0)
requests (2.27.1)
requests-unixsocket (0.1.5)
scipy (0.19.1)
SecretStorage (2.3.1)
setuptools (39.0.1)
simplejson (3.13.2)
six (1.16.0)
ssh-import-id (5.7)
system-service (0.3)
systemd-python (234)
tensorrt (8.0.1.6)
ubuntu-drivers-common (0.0.0)
uff (0.6.9)
unity-scope-calculator (0.1)
unity-scope-chromiumbookmarks (0.1)
unity-scope-colourlovers (0.1)
unity-scope-devhelp (0.1)
unity-scope-firefoxbookmarks (0.1)
unity-scope-manpages (0.1)
unity-scope-openclipart (0.1)
unity-scope-texdoc (0.1)
unity-scope-tomboy (0.1)
unity-scope-virtualbox (0.1)
unity-scope-yelp (0.1)
unity-scope-zotero (0.1)
urllib3 (1.26.18)
urwid (2.0.1)
wadllib (1.3.2)
webencodings (0.5)
wheel (0.37.1)
xkit (0.0.0)
youtube-dl (2018.3.14)
zope.interface (4.3.2)
```

**Comment by ViktorPavlovA** [comment]
Please add in where you used (module subprocess ) try - except variant with `universal_newlines=True` instead `text=True`. It works for me.

**Comment by ViktorPavlovA** [comment]
I got it. it is for raspberry pi . Not for jetson nano. No more question. )
